// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "aws-practitioner-js-4-node",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductType": {
      "properties": {
        "id": {
          "title": "ProductType.id",
          "type": "string"
        },
        "title": {
          "title": "ProductType.title",
          "type": "string"
        },
        "count": {
          "title": "ProductType.count",
          "type": "number"
        },
        "price": {
          "title": "ProductType.price",
          "type": "number"
        },
        "description": {
          "title": "ProductType.description",
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "count",
        "price",
        "description"
      ],
      "additionalProperties": false,
      "title": "ProductType",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "host": "6me96m3are.execute-api.eu-west-1.amazonaws.com/dev"
};