// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "aws-practitioner-js-4-node",
    "version": "1"
  },
  "paths": {
    "/scripts/loadInitialData": {
      "get": {
        "summary": "loadInitialData",
        "description": "",
        "operationId": "loadInitialData.get.scripts/loadInitialData",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateProductPayload"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "count",
        "price",
        "description"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Stock": {
      "properties": {
        "productId": {
          "title": "Stock.productId",
          "type": "string"
        },
        "count": {
          "title": "Stock.count",
          "type": "number"
        }
      },
      "required": [
        "productId",
        "count"
      ],
      "additionalProperties": false,
      "title": "Stock",
      "type": "object"
    },
    "CreateProductPayload": {
      "title": "CreateProductPayload"
    }
  },
  "securityDefinitions": {},
  "host": "6me96m3are.execute-api.eu-west-1.amazonaws.com/dev"
};